name: Product Firmware Build

on:
  push:
    paths:
      - product-firmware/**
      - .github/workflows/product-firmware-build.yaml

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Compile application
        id: compile
        uses: particle-iot/compile-action@v1
        with:
          particle-access-token: ${{ secrets.PARTICLE_ACCESS_TOKEN_21813 }}
          particle-platform-name: 'argon'
          device-os-version: '4.x'
          sources-folder: 'product-firmware'

      - name: Upload artifacts
        uses: actions/upload-artifact@v3
        with:
          name: product-firmware-argon-${{ steps.compile.outputs.device-os-version }}
          path: ${{ steps.compile.outputs.firmware-path }}

      - name: Flash development device on main branch
        if: github.ref == 'refs/heads/main'
        uses: particle-iot/flash-device-action@v1
        with:
          particle-access-token: ${{ secrets.PARTICLE_ACCESS_TOKEN_21813 }}
          device-id: 'e00fce68ae40842eb4570366'
          firmware-path: ${{ steps.compile.outputs.firmware-path }}
